name: Using containers
on:
  workflow_dispatch:

jobs:
  container-test-job:
    name: Install conda (os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/i4ds/mambabuild-docker:latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Show conda info
        run: |
          conda info
          conda config --append channels i4ds
          conda config --append channels nvidia/label/cuda-11.7.0
          conda config --append channels conda-forge
