name: Using containers
on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/i4ds/mambabuild-docker:latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Show conda info
        run: |
          conda info
          conda config --append channels i4ds
          conda config --append channels nvidia/label/cuda-11.7.0
          conda config --append channels conda-forge
