name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow-dispatch]
jobs:
  Explore-Actions:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: echo "Job was triggered by a ${{ github.event_name}} event"
      - run: echo "The name of your branch is ${{ github.ref }} and the repository is ${{ github.repository }}"

