name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-Actions:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: echo "Job was triggered by a ${{ github.event_name}} event"
      - run: echo "The name of your branch is ${{ github.ref }} and the repository is ${{ github.repository }}"

    example-1:
      name: Ex15 (os=${{ matrix.os }})
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-24.04-arm"]
          python-version: ["3.9", "3.10", "3.10"]
      steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
