name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-Actions:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: echo "Job was triggered by a ${{ github.event_name}} event"
      - run: echo "The name of your branch is ${{ github.ref }} and the repository is ${{ github.repository }}"

  Conda-Basic-Installation:
    name: job1 (os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04-arm"]
        python-version: ["3.9"]
    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        conda-remove-defaults: true
        python-version: ${{ matrix.python-version }}
    - name: Check ARM
      shell: bash -el {0}
      run: |
        conda install -y python
        python -c "import platform; assert platform.machine() != 'aarch64', platform.machine()"
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list
